# Generated by Django 3.2 on 2021-04-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
