# Generated by Django 3.2 on 2021-04-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agoranews_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agoranews',
            name='links',
            field=models.URLField(),
        ),
    ]
